name: Ad-hoc Docker Image

on:
  # This line enables manual triggering of this workflow.
  workflow_dispatch:

jobs:
  server-build:
    name: server-build
    uses: ./.github/workflows/server-build.yml
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}
      skip-tests: true

  client-build:
    name: client-build
    uses: ./.github/workflows/client-build.yml
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}

  rts-build:
    name: rts-build
    uses: ./.github/workflows/rts-build.yml
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}

  package:
    needs: [server-build, client-build, rts-build]
    runs-on: ubuntu-latest
    # Set permissions since we're using OIDC token authentication between Depot and GitHub
    permissions:
      contents: read
      id-token: write

    steps:
      # Check out the specified branch in case this workflow is called by another workflow
      - name: Checkout the specified branch
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ inputs.branch }}

      - name: Download the react build artifact
        uses: actions/download-artifact@v4
        with:
          name: client-build
          path: app/client

      - name: Unpack the client build artifact
        if: steps.run_result.outputs.run_result != 'success'
        run: |
          mkdir -p app/client/build
          tar -xvf app/client/build.tar -C app/client/build

      - name: Download the server build artifact
        uses: actions/download-artifact@v4
        with:
          name: server-build
          path: app/server/dist

      - name: Download the rts build artifact
        uses: actions/download-artifact@v4
        with:
          name: rts-dist
          path: app/client/packages/rts/dist

      - name: Untar the rts folder
        run: |
          tar -xvf app/client/packages/rts/dist/rts-dist.tar -C app/client/packages/rts/
          echo "Cleaning up the tar files"
          rm app/client/packages/rts/dist/rts-dist.tar

      - name: Generate info.json
        run: |
          if [[ -f scripts/generate_info_json.sh ]]; then
            scripts/generate_info_json.sh
          fi

      - name: Place server artifacts-es
        run: |
          run: |
          if [[ -f scripts/prepare_server_artifacts.sh ]]; then
            scripts/prepare_server_artifacts.sh
          else
            echo "No script found to prepare server artifacts"
            exit 1
          fi

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Set Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ secrets.YCR_REGESTRY }}/appsmith,enable=true
          tags: |
            type=raw,value=latest
            type=raw,value={{branch}}
            type=raw,value={{sha}}-{{date 'DD.MM.YYYY-HH.mm'}}
  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            BASE=appsmith/appsmith-ee
            # APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }}
          tags: ${{ steps.meta.outputs.tags }}
